name: Print event
on: [ push,pull_request,deployment,release,delete,deployment_status ]
jobs:
  print-event:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
